kind: ServiceAccount
apiVersion: v1
metadata:
  name: daskernetes
  namespace: jupyter


---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: daskernetes
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: daskernetes
subjects:
- kind: ServiceAccount
  name: daskernetes
  namespace: jupyter
roleRef:
  kind: Role
  name: daskernetes
  apiGroup: rbac.authorization.k8s.io
