apiVersion: v1
kind: Service
metadata:
  name: pycsw
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: pycsw
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    name: pycsw
    component: pycsw
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
