kind: ConfigMap
apiVersion: v1
metadata:
  name: daskernetes-config
data:
  worker-template.yaml: |-
    metadata:
    spec:
      restartPolicy: Never
      containers:
        - name: dask-worker
          image: informaticslab/singleuser-notebook:latest
          args: [dask-worker, --nthreads, '1', --no-bokeh, --memory-limit, 3GB, --death-timeout, '60']
          resources:
            limits:
              cpu: "1"
              memory: 3G
            requests:
              cpu: "1"
              memory: 3G
          volumeMounts:
            - name: s3
              mountPath: /s3
            - name: scratch
              mountPath: /scratch
      volumes:
        - name: s3
          flexVolume:
            driver: "informaticslab/pysssix-flex-volume"
            options:
              readonly: "true"
        - name: scratch
          flexVolume:
            driver: "informaticslab/goofys-flex-volume"
            options:
              bucket: "informatics-pangeo-scratch"
              dirMode: "0777"
              fileMode: "0777"
