kind: ConfigMap
apiVersion: v1
metadata:
  name: daskernetes-config
data:
  worker-template.yaml: |-
    metadata:
    spec:
      restartPolicy: Never
      containers:
      - args: [dask-worker, --nthreads, '2', --no-bokeh, --memory-limit, 7GB, --death-timeout, '60']
        image: informaticslab/singleuser-notebook:latest
        name: dask-worker
        resources:
          limits:
            cpu: "1.75"
            memory: 6G
          requests:
            cpu: "1.75"
            memory: 6G
        storage:
          extraVolumes:
          - name: s3
            flexVolume:
              driver: "informaticslab/s3-fuse-flex-volume"
              options:
                readonly: "true"
          extraVolumeMounts:
          - name: s3
            mountPath: /s3
